name: dstore_middleware_dio
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.13.0 <4.0.0"
resolution: workspace
dependencies:
  dstore:
  dio:
dev_dependencies:
  pedantic:
