name: dstore_test
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=3.13.0 <4.0.0"
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  dstore:
  async:
  test:

dev_dependencies:
  pedantic: 1.10.0
  build_runner:
  grinder: 0.9.0-nullsafety.0
  json_serializable:
  test:

# dependency_overrides:
#   meta:
