       // This file is autogenerated on 2021-06-11 14:46:05.079649 dont modify directly 

       final Map<String,Map<String,dynamic>> platformsSourceCode = {"android":{"name":"android","files":{},"subfolders":[]},"ios":{"name":"ios","files":{},"subfolders":[]},"web":{"name":"web","files":{},"subfolders":[]},"macos":{"name":"macos","files":{},"subfolders":[]}};
      
      