name: dstore_dgraph
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.13.0-0 <3.0.0"
dependencies:
  collection: 1.15.0
  dstore_annotation:
    path: ../dstore_annotation

dev_dependencies:
  pedantic: 1.10.0
  test:
  time:   
  build_runner: 
  grinder: 0.9.0-nullsafety.0
