name: dstore_generator
version: 0.0.1
description: >-
  dstore.
homepage: https://github.com/chandu0101/dstore
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  analyzer: 5.5.0
  build: ^2.3.1
  meta: 1.7.0
  source_gen: ^1.2.7
  gql: ^0.13.0 
  crypto: 
  dio: ^4.0.0
  collection:
  timing:
  yaml:    
  ansicolor: 2.0.0-nullsafety.0
  tuple: ^2.0.0
  open_api_schema:
    path: /Users/chandrasekharkode/Desktop/kode/programming/dart_projects/open_api_schema
  path_to_regexp: 
  dstore_annotation:
    path: /Users/chandrasekharkode/Desktop/kode/programming/dart_projects/dstore/packages/dstore_annotation
  dstore_dgraph:
    path: /Users/chandrasekharkode/Desktop/kode/programming/dart_projects/dstore/packages/dgraph
  dotenv:
      

dev_dependencies:
  pedantic: 1.10.0
  build_runner: ^2.0.4
  grinder: 
  json_serializable: ^6.6.1
  test: 
  
    
# dependency_overrides: 
#   test: 1.17.11